2020-04-10 18:29:29,664 ERROR: Exception on /bulk_upload [POST] [in c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\alexander.danson\Documents\GitHub\Activity_viewer\app\main\routes.py", line 73, in bulk_upload
    form.file.data.save(url_for('static.uploads') + filename)
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask\app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask\helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\werkzeug\routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'static.uploads'. Did you mean 'main.bulk_upload' instead?
2020-04-10 18:33:39,035 INFO: Activity_Viewer startup [in C:\Users\alexander.danson\Documents\GitHub\Activity_viewer\app\__init__.py:68]
2020-04-10 18:33:48,747 ERROR: Exception on /bulk_upload [POST] [in c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\alexander.danson\Documents\GitHub\Activity_viewer\app\main\routes.py", line 73, in bulk_upload
    form.file.data.save(url_for('static', filename=filename))
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\werkzeug\datastructures.py", line 2800, in save
    dst = open(dst, "wb")
FileNotFoundError: [Errno 2] No such file or directory: '/static/activities.csv'
2020-04-10 18:37:39,471 INFO: Activity_Viewer startup [in C:\Users\alexander.danson\Documents\GitHub\Activity_viewer\app\__init__.py:68]
