2020-03-10 16:38:31,223 ERROR: Exception on /index [GET] [in c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask_login\utils.py", line 260, in decorated_view
    return current_app.login_manager.unauthorized()
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask_login\login_manager.py", line 175, in unauthorized
    redirect_url = make_login_url(login_view, next_url=request.url)
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask_login\utils.py", line 112, in login_url
    base = expand_login_view(login_view)
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask_login\utils.py", line 89, in expand_login_view
    return url_for(login_view)
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask\app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask\helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\werkzeug\routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'auth.login' instead?
2020-03-10 17:04:02,004 INFO: Activity_Viewer startup [in C:\Users\alexander.danson\Documents\GitHub\Activity_viewer\app\__init__.py:58]
2020-03-10 17:04:03,120 ERROR: Exception on /index [GET] [in c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask_login\utils.py", line 260, in decorated_view
    return current_app.login_manager.unauthorized()
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask_login\login_manager.py", line 175, in unauthorized
    redirect_url = make_login_url(login_view, next_url=request.url)
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask_login\utils.py", line 112, in login_url
    base = expand_login_view(login_view)
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask_login\utils.py", line 89, in expand_login_view
    return url_for(login_view)
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask\app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\flask\helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "c:\users\alexander.danson\documents\github\activity_viewer\venv\lib\site-packages\werkzeug\routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'auth.login' instead?
2020-03-10 17:06:31,288 INFO: Activity_Viewer startup [in C:\Users\alexander.danson\Documents\GitHub\Activity_viewer\app\__init__.py:58]
2020-03-12 10:16:23,841 INFO: Activity_Viewer startup [in C:\Users\alexander.danson\Documents\GitHub\Activity_viewer\app\__init__.py:60]
2020-03-12 10:20:55,175 INFO: Activity_Viewer startup [in C:\Users\alexander.danson\Documents\GitHub\Activity_viewer\app\__init__.py:60]
